version: "3.3"

services:

  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'library'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-db:/var/lib/mysql
    networks:
      - rede_node

  nestapi:
    container_name: node-nestjs
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/app
    networks:
      - rede_node
    depends_on:
      - db
    command: bash -c "tail -f /dev/null"  # <- faz o container funcionar sem rodar nada

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"
    networks:
      - rede_node

volumes:
  mysql-db:

networks:
  rede_node:
    driver: bridge
